import { access, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const publicRoots = ['README.md', 'CONTRIBUTING.md', 'SECURITY.md', 'THIRD_PARTY_NOTICES.md', 'docs'] as const;
const initOptions = [
  '--profile <profile>',
  '--dry-run',
  '--yes',
  '--no-global',
  '--no-orca-registration',
  '--no-github-mutations',
  '--json',
] as const;

describe('public documentation contract', () => {
  it('documents the shipped command surface, V1 profiles, and ownership boundaries', async () => {
    const readme = await readFile(path.join(root, 'README.md'), 'utf8');

    expect(readme).toContain('npx @dyewolf/agent-orchestration-kit@latest init');
    expect(readme).toContain('Node.js 22 or newer');
    expect(readme).toContain('Orca 1.4.190');
    expect(readme).toContain('codex-only');
    expect(readme).toContain('claude-coordinator');
    expect(readme).toContain('claude-only');
    expect(readme).toContain('codex-coordinator');
    expect(readme).toContain('Pending live validation');
    expect(readme).toContain('effort intentionally unset');
    expect(readme).toContain('does not install tools');
    expect(readme).toContain('not affiliated with');
    for (const option of initOptions) expect(readme).toContain(`\`${option}\``);
  });

  it('documents the canonical repository, installed V1 paths, and generated markers', async () => {
    const readme = await readFile(path.join(root, 'README.md'), 'utf8');

    expect(readme).toContain('https://github.com/DYEWolf/agent-orchestration-kit');
    for (const installedPath of [
      'AGENTS.md',
      '.agent-orchestration-kit/config.yaml',
      '.agent-orchestration-kit/manifest.json',
      '.agents/THIRD_PARTY_NOTICES.md',
      '.agents/skills/<skill>/SKILL.md',
      '.agents/skills/<skill>/agents/openai.yaml',
      '.agents/skills/<skill>/PROVENANCE.json',
      'docs/agents/orca-execution.md',
      'docs/agents/issue-tracker.md',
      'docs/agents/skill-overrides.md',
      'docs/agents/domain.md',
      'CLAUDE.md',
      '.claude/skills/<skill>/SKILL.md',
    ]) {
      expect(readme).toContain(`\`${installedPath}\``);
    }

    expect(readme).toContain('<!-- Generated by @dyewolf/agent-orchestration-kit. V1 does not update this file automatically. -->');
    expect(readme).toContain('<!-- agent-orchestration-kit:start version="1" -->');
    expect(readme).toContain('<!-- agent-orchestration-kit:end -->');
  });

  it('packs only the documented runtime, templates, notices, and public documentation roots', async () => {
    const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8')) as { files: string[] };
    expect(packageJson.files).toEqual([
      'dist',
      'templates',
      'LICENSE',
      'THIRD_PARTY_NOTICES.md',
      'README.md',
      'CONTRIBUTING.md',
      'SECURITY.md',
      'docs',
    ]);
  });

  it('has resolvable relative links in every packed Markdown document', async () => {
    const documents = await publicMarkdownFiles(root);
    for (const document of documents) {
      const content = await readFile(document, 'utf8');
      for (const target of relativeMarkdownTargets(content)) {
        const withoutFragment = target.split('#', 1)[0]!.split('?', 1)[0]!;
        if (withoutFragment === '') continue;
        await expect(access(path.resolve(path.dirname(document), decodeURIComponent(withoutFragment)))).resolves.toBeUndefined();
      }
    }
  });
});

async function publicMarkdownFiles(directory: string, rootLevel = true): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(directory, { withFileTypes: true });
  for (const entry of entries) {
    if (rootLevel && !publicRoots.includes(entry.name as typeof publicRoots[number])) continue;
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await publicMarkdownFiles(absolutePath, false));
    else if (entry.isFile() && entry.name.endsWith('.md')) files.push(absolutePath);
  }
  return files;
}

function relativeMarkdownTargets(markdown: string): string[] {
  return [...markdown.matchAll(/!?\[[^\]]*\]\((?:<)?([^\s)>]+)(?:>)?(?:\s+[^)]*)?\)/gu)]
    .map((match) => match[1]!)
    .filter((target) => !/^(?:[a-z][a-z+.-]*:|\/\/|#)/iu.test(target));
}
