import { stringify as stringifyYaml } from 'yaml';
import type { WorkflowConfig } from '../config/schema.js';
import { BUNDLE_VERSION, CLI_VERSION } from '../version.js';
import { sha256 } from '../shared/hash.js';
import type { Manifest, ManifestEntry } from '../workflow-project/manifest.js';
import { MANAGED_BLOCK_END, MANAGED_BLOCK_START } from './managed-block.js';
import { renderSkillArtifacts, renderSkillNotices } from './skill-bundle.js';

export interface DesiredArtifact {
  readonly path: string;
  readonly content: string;
  readonly ownership: 'full' | 'managed-block';
}

const generatedHeader = '<!-- Generated by @dyewolf/orca-kit. V1 does not update this file automatically. -->';

export function renderDesiredArtifacts(config: WorkflowConfig): DesiredArtifact[] {
  const artifacts: DesiredArtifact[] = [
    {
      path: 'AGENTS.md',
      ownership: 'managed-block',
      content: renderAgentsBlock(config),
    },
    {
      path: '.orca-kit/config.yaml',
      ownership: 'full',
      content: `# Generated by @dyewolf/orca-kit. V1 does not update this file automatically.\n${stringifyYaml(config, { lineWidth: 0, aliasDuplicateObjects: false })}`,
    },
    {
      path: '.agents/THIRD_PARTY_NOTICES.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n${renderSkillNotices()}`,
    },
    {
      path: 'docs/agents/orca-execution.md',
      ownership: 'full',
      content: renderOrcaExecutionDoc(),
    },
    {
      path: 'docs/agents/issue-tracker.md',
      ownership: 'full',
      content: renderIssueTrackerDoc(),
    },
    {
      path: 'docs/agents/skill-overrides.md',
      ownership: 'full',
      content: renderSkillOverridesDoc(),
    },
    {
      path: 'docs/agents/domain.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n# Project domain\n\nRecord repository-specific domain language, invariants, boundaries, and architectural decisions here. Do not copy product rules from unrelated repositories.\n`,
    },
  ];

  artifacts.push(...renderSkillArtifacts());

  const manifestEntries = artifacts
    .map<ManifestEntry>((artifact) => ({
      path: artifact.path,
      hash: sha256(artifact.content),
      ownership: artifact.ownership,
    }))
    .sort((a, b) => a.path.localeCompare(b.path));

  const manifest: Manifest = {
    schemaVersion: 1,
    cliVersion: CLI_VERSION,
    bundleVersion: BUNDLE_VERSION,
    files: manifestEntries,
  };

  artifacts.push({
    path: '.orca-kit/manifest.json',
    ownership: 'full',
    content: `${JSON.stringify(manifest, null, 2)}\n`,
  });

  return artifacts.sort((a, b) => a.path.localeCompare(b.path));
}

function renderAgentsBlock(config: WorkflowConfig): string {
  const routeLines = Object.entries(config.routing).map(([role, route]) => {
    const effort = route.effort === undefined ? '' : `, effort ${route.effort}`;
    const freshness = route.freshSession === true ? ', fresh session' : '';
    return `- ${role}: ${route.harness} / ${route.model.value} (${route.model.resolution}${effort}${freshness})`;
  });

  return [
    MANAGED_BLOCK_START,
    '',
    '# Orca workflow constitution',
    '',
    'Orca is the execution source of truth. One coordinator owns the user conversation and delegates bounded Tasks. Workers never create Runs, Tasks, worktrees, or nested agents.',
    '',
    'GitHub Issues are durable work units. Implementation begins only from a claimed, approved, executable, unblocked Issue. Use deterministic verification, explicit decision gates, risk-based review, and worktrees only when ownership does not overlap.',
    '',
    'One implementation Issue owns exactly one Orca execution Run. Cross-Issue dependencies live in GitHub; dependencies among Tasks for one Issue live in Orca.',
    '',
    '## Phase gates',
    '',
    'The default flow is grill-with-docs → to-spec → to-tickets → implement. wayfinder precedes it when the destination is too foggy for one session. Never silently advance between phases. Pause for approval at understanding, specification, and ticket-breakdown gates even when an end-to-end flow was authorized.',
    '',
    '## Worker contract',
    '',
    '- Workers perform only the bounded Dispatch they receive and return concrete evidence exactly once.',
    '- Workers do not create Runs, Tasks, worktrees, branches, or nested agents.',
    '- The coordinator owns Issue mutation, Task DAGs, gates, worktree placement, integration, and the user conversation.',
    '- Parallelize only independent Tasks with non-overlapping ownership.',
    '',
    `Maximum active implementation workers: ${config.execution.maxImplementationWorkers}. Review policy: ${config.execution.reviewPolicy}.`,
    '',
    '## Routing',
    '',
    ...routeLines,
    '',
    'Reviewers report SHIP, FIX_FIRST, or RETHINK and do not implement their own corrections.',
    '',
    'Follow `docs/agents/orca-execution.md` for lifecycle, `docs/agents/issue-tracker.md` for GitHub operations, and `docs/agents/skill-overrides.md` for the pinned skill bundle contract.',
    '',
    MANAGED_BLOCK_END,
  ].join('\n');
}

function renderOrcaExecutionDoc(): string {
  return `${generatedHeader}

# Orca execution

Orca owns Runs, Tasks, Dispatches, gates, mailboxes, workers, and lifecycle. One
coordinator owns the user conversation and the Issue-owned Run.

## Mapping

Each GitHub implementation Issue maps to exactly one Orca execution Run. A Run
may contain evidence, implementation, verification, correction, and independent
review Tasks. Cross-Issue dependencies stay in GitHub; dependencies inside the
Issue stay in Orca.

## Dispatch rules

- Create bounded Tasks with explicit ownership, acceptance evidence, and
  dependencies before dispatching.
- Workers never create Runs, Tasks, worktrees, branches, or nested agents.
- At most three implementation workers are active by default. Parallel Tasks
  must be independent and must not own overlapping files or state.
- A worker sends one terminal completion carrying what changed, verification,
  files touched, and remaining risk, then stops.
- Questions use Orca ask/reply. Timeouts are checkpoints, not failures.
- The coordinator releases or deliberately reuses every settled worker.

## Escalation and review

Escalation is bounded worker → judgment worker → architectural authority and is
used only as needed, not as a ritual pipeline. Independent review is risk-based.
A reviewer is fresh for high-risk work, reports SHIP, FIX_FIRST, or RETHINK, and
does not implement its own corrections.

Deterministic tests, typechecking, build output, and exact command receipts are
preferred evidence. Claims without evidence do not close an Issue.
`;
}

function renderIssueTrackerDoc(): string {
  return `${generatedHeader}

# GitHub Issue tracker

GitHub Issues are the only durable work units in v1. Agents use the authenticated
\`gh\` CLI at runtime. orca-kit itself does not create Issues, commits, branches,
pushes, or pull requests.

## Required labels

- \`ready-for-agent\`
- \`wontfix\`
- \`wayfinder:map\`
- \`wayfinder:research\`
- \`wayfinder:prototype\`
- \`wayfinder:grilling\`
- \`wayfinder:task\`

Missing labels make the installed workflow incomplete. Phase 4 adds confirmed
label creation and remote doctor checks; until then they must be created by the
repository owner.

## Issue contract

An implementation Issue contains the approved objective, acceptance criteria,
dependencies, decisions, verification evidence, review result, and resolution.
Implementation begins only when the Issue is open, claimed, approved,
executable, unblocked, and labelled \`ready-for-agent\`.

Read full Issue bodies and comments before acting. Preserve parent Issues unless
the active skill explicitly owns their mutation. Record progress and decisions
as comments rather than inventing redundant status labels. Close an Issue only
after deterministic verification and any risk-required review pass.

to-tickets may create Issues after the user approves the breakdown. wayfinder may
create and update its map and decision Issues. implement may comment, update the
claim, and close its owned implementation Issue. Those are agent runtime actions,
not CLI initialization actions.
`;
}

function renderSkillOverridesDoc(): string {
  return `${generatedHeader}

# Skill overrides

Canonical editable content lives under \`.agents/skills/\`. Each skill contains a
pinned upstream procedure, a structural Orca overlay, Codex discovery metadata,
and \`PROVENANCE.json\` with the exact upstream commit and hashes.

The Orca overlay has precedence when upstream wording assumes direct user waits,
a Skill tool, nested subagents, background agents, fresh branches, or automatic
commits. The coordinator translates those actions into Orca Tasks, Dispatches,
ask/reply, and explicit mutation ownership. Workers never nest delegation.

Project invariants belong in \`AGENTS.md\`; reusable procedures belong in skills.
The generated files become user-owned after installation. V1 does not update or
merge them, and a later init refuses local drift rather than overwriting it.
`;
}
