import { stringify as stringifyYaml } from 'yaml';
import type { WorkflowConfig } from '../config/schema.js';
import { BUNDLE_VERSION, CLI_VERSION } from '../version.js';
import { sha256 } from '../shared/hash.js';
import type { Manifest, ManifestEntry } from '../workflow-project/manifest.js';
import { MANAGED_BLOCK_END, MANAGED_BLOCK_START } from './managed-block.js';

export interface DesiredArtifact {
  readonly path: string;
  readonly content: string;
  readonly ownership: 'full' | 'managed-block';
}

const generatedHeader = '<!-- Generated by @dyewolf/orca-kit. V1 does not update this file automatically. -->';

export function renderDesiredArtifacts(config: WorkflowConfig): DesiredArtifact[] {
  const artifacts: DesiredArtifact[] = [
    {
      path: 'AGENTS.md',
      ownership: 'managed-block',
      content: renderAgentsBlock(config),
    },
    {
      path: '.orca-kit/config.yaml',
      ownership: 'full',
      content: `# Generated by @dyewolf/orca-kit. V1 does not update this file automatically.\n${stringifyYaml(config, { lineWidth: 0 })}`,
    },
    {
      path: '.agents/THIRD_PARTY_NOTICES.md',
      ownership: 'full',
      content: renderProjectNotices(),
    },
    {
      path: 'docs/agents/orca-execution.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n# Orca execution\n\nOrca owns Runs, Tasks, Dispatches, gates, mailboxes, workers, and lifecycle. One coordinator owns the user conversation. Workers perform bounded tasks, return evidence once, and never create nested workers.\n`,
    },
    {
      path: 'docs/agents/issue-tracker.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n# GitHub Issue tracker\n\nGitHub Issues are the durable work units. One implementation Issue owns exactly one Orca execution Run and may contain multiple Tasks. Cross-Issue dependencies live in GitHub; intra-Issue dependencies live in Orca.\n`,
    },
    {
      path: 'docs/agents/skill-overrides.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n# Skill overrides\n\nCanonical editable skill content lives under \`.agents/skills/\`. Project invariants belong in \`AGENTS.md\`; skill files define reusable procedures. Local edits are user-owned after installation.\n`,
    },
    {
      path: 'docs/agents/domain.md',
      ownership: 'full',
      content: `${generatedHeader}\n\n# Project domain\n\nRecord repository-specific domain language, invariants, boundaries, and architectural decisions here. Do not copy product rules from unrelated repositories.\n`,
    },
  ];

  const manifestEntries = artifacts
    .map<ManifestEntry>((artifact) => ({
      path: artifact.path,
      hash: sha256(artifact.content),
      ownership: artifact.ownership,
    }))
    .sort((a, b) => a.path.localeCompare(b.path));

  const manifest: Manifest = {
    schemaVersion: 1,
    cliVersion: CLI_VERSION,
    bundleVersion: BUNDLE_VERSION,
    files: manifestEntries,
  };

  artifacts.push({
    path: '.orca-kit/manifest.json',
    ownership: 'full',
    content: `${JSON.stringify(manifest, null, 2)}\n`,
  });

  return artifacts.sort((a, b) => a.path.localeCompare(b.path));
}

function renderAgentsBlock(config: WorkflowConfig): string {
  const routeLines = Object.entries(config.routing).map(([role, route]) => {
    const effort = route.effort === undefined ? '' : `, effort ${route.effort}`;
    const freshness = route.freshSession === true ? ', fresh session' : '';
    return `- ${role}: ${route.harness} / ${route.model.value} (${route.model.resolution}${effort}${freshness})`;
  });

  return [
    MANAGED_BLOCK_START,
    '',
    '# Orca workflow constitution',
    '',
    'Orca is the execution source of truth. One coordinator owns the user conversation and delegates bounded Tasks. Workers never create Runs, Tasks, worktrees, or nested agents.',
    '',
    'GitHub Issues are durable work units. Implementation begins only from a claimed, approved, executable, unblocked Issue. Use deterministic verification, explicit decision gates, risk-based review, and worktrees only when ownership does not overlap.',
    '',
    `Maximum active implementation workers: ${config.execution.maxImplementationWorkers}. Review policy: ${config.execution.reviewPolicy}.`,
    '',
    '## Routing',
    '',
    ...routeLines,
    '',
    'Reviewers report SHIP, FIX_FIRST, or RETHINK and do not implement their own corrections.',
    '',
    MANAGED_BLOCK_END,
  ].join('\n');
}

function renderProjectNotices(): string {
  return `${generatedHeader}\n\n# Third-party notices\n\nThe complete Matt Pocock skill provenance and MIT license will accompany the reviewed Phase 2 bundle. No third-party skill bodies are rendered by the Phase 1 planner.\n\nThis project is not affiliated with, endorsed by, or an official product of Orca or its maintainers.\n`;
}
